language: node_js

node_js:
  - '10'
  - '12'
  - '14'
  - '16'
  - 'node'
  - 'lts/*'

script:
  - npm run lint-ci
  - npm run test-ci

notifications:
  email:
    on_success: never
    on_failure: always
